baseurl = "https://www.petzsch.eu"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "petzsch.eu"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "petzsch"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Welcome on my personal webpage."
  logo = "img/markus-pic.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Markus Petzsch"
  email = "markus@petzsch.eu"
  facebook = "petzsch"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "petzsch"
  github = "petzsch"
  twitter = "petzsch"
  reddit = "petzsch"
  linkedin = "petzsch"
  xing = "Markus_Petzsch"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "services"
    name = "Services"
    weight = 2

[[menu.main]]
    parent = "services"
    name = "ISPConfig"
    url = "https://ispconfig.petzsch.eu:8443"
    weight = 1

[[menu.main]]
    parent = "services"
    name = "Nextcloud"
    url = "https://cloud.petzsch.eu"
    weight = 2

[[menu.main]]
    parent = "services"
    name = "Webmail"
    url = "https://webmail.petzsch.eu"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
